'''
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

SOL: simply use two dictionary to record the appearing times of each alphabet. 
return the one with the value in t that more than in s. 
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        d = collections.defaultdict(int)
        d2 = collections.defaultdict(int)
        for i in s:
            if i not in d:
                d[i] = 1
            else:
                d[i] +=1
        
        for i in t:
            if i not in d2:
                d2[i] = 1
            else: 
                d2[i] +=1
        
        for key in d2:
            if d2[key] > d[key]:
                return key